sudo: required

matrix:
    include:
        - dist: focal

language: python
python:
 - '3.10'

install:
 - pip install tox
 - pip install python-coveralls

script:
 - tox

after_success:
  - coveralls
