#!/usr/bin/env python3

from unittest import TestCase, main

from website import (
    WebsiteDeploymentSpec,
    WebsiteDeploymentTest,
)


class JammyWebsiteDeploymentTest(WebsiteDeploymentTest, TestCase):

    spec = WebsiteDeploymentSpec(series="jammy", storage=False)


if __name__ == "__main__":
    main()
