#!/usr/bin/env python3

from unittest import TestCase, main

from slave import (
    SlaveDeploymentSpec,
    SlaveDeploymentTest,
)


class JammySlaveDeploymentTest(SlaveDeploymentTest, TestCase):

    spec = SlaveDeploymentSpec(series="jammy")


if __name__ == "__main__":
    main()
