#!/usr/bin/env python3

from unittest import TestCase, main
from extension import ExtensionDeploymentSpec, ExtensionDeploymentTest


class JammyExtensionDeploymentTest(ExtensionDeploymentTest, TestCase):

    spec = ExtensionDeploymentSpec(series="jammy")


if __name__ == "__main__":
    main()
