#!/usr/bin/env python3

from unittest import TestCase, main

from nrpe import (
    NRPEDeploymentSpec,
    NRPEDeploymentTest,
)


class JammyNRPEDeploymentTest(NRPEDeploymentTest, TestCase):

    spec = NRPEDeploymentSpec(series="jammy")


if __name__ == "__main__":
    main()
